### ISSUE TITLE
Npm package doesn't work Store dependency could not be injected.

### ISSUE THREAD

**Issue by jantilburgh** [syncrea/ngrx-store-forms#1]
Tried the NPM package but it gives a "Store dependency could not be injected" like exception. The reason for this is dat the js bundle in the NPM package also contains a version of the @ngrx/store library. Tried to create a PR but don't have persmissions so there is the fix ...

ng-package.json:
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "@ngrx/store": "@ngrx/store",
      "@ngrx/store-devtools": "@ngrx/store-devtools",
      "@ngrx/effects": "@ngrx/effects",
      "rxjs": "rxjs"
    }
  }
}

**Comment by gionkunz** [comment]
Hi! Thanks, sorry I didn't test the package yet :-))) I'll give it a go and push a new version. I think in GitHub you always need to fork first before you can create PRs

**Comment by jantilburgh** [comment]
Indeed a fork needs to be created first. https://github.com/syncrea/ngrx-store-forms/pull/2

**Comment by gionkunz** [comment]
Thanks for the PR! I've looked a bit closed at the problem and it was a huge digging action as all those libraries are in such movement. It seems that the current ng-packagr version 1.6 is not compatible with the latest RxJS version too and we need to add some of the externals mappings ourself. This should all be solved with ng-packagr 2.

**Comment by gionkunz** [comment]
0.0.3 is on NPM

**Comment by jantilburgh** [comment]
Wow what a big list ! I'll try the package, thanks!
