### ISSUE TITLE
FormArray

### ISSUE THREAD

**Issue by jantilburgh** [syncrea/ngrx-store-forms#6]
Hi,

Does the library handle formArrays or what would be a good approach for this ?

**Comment by gionkunz** [comment]
We need to check that. Pre-requisite is a top-level `FormGorup`. If `getRawValues` and `setValues` `patchValues` work consistent, it should work out-of-the-box.

**Comment by jantilburgh** [comment]
PR with example of the issue https://github.com/syncrea/ngrx-store-forms/pull/8

**Comment by gionkunz** [comment]
Should work as documented within the tests

**Comment by jantilburgh** [comment]
But what if you load data using the HttpClient from an effect, how would that work ?

**Comment by gionkunz** [comment]
I've added a basic example within the App. Check out https://github.com/syncrea/ngrx-store-forms/tree/master/src/app/user-form

**Comment by gionkunz** [comment]
This example subscribes on the success action of the server load to fill in the initial form group
